# Generated by Django 4.1.2 on 2022-10-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigoPedido',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='codigo_plato',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.tipoentrega'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.tipomenu'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo_plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.tipoplato'),
        ),
    ]
