# Generated by Django 4.1.2 on 2022-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('domCalle', models.CharField(max_length=100)),
                ('domNumero', models.CharField(max_length=4, unique=True)),
                ('domBarrio', models.CharField(max_length=100)),
                ('domLocalidad', models.CharField(max_length=100)),
                ('domObservacion', models.CharField(max_length=200)),
                ('domCodZona', models.CharField(choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste')], max_length=9)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
