# Generated by Django 4.1.2 on 2022-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=8, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_fijo', models.CharField(max_length=15)),
                ('telefono_celular', models.CharField(max_length=15)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField()),
                ('localidad', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('vigencia_carnet', models.DateField()),
                ('patente', models.CharField(max_length=10)),
                ('codigo_zona', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=8, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_fijo', models.CharField(max_length=15)),
                ('telefono_celular', models.CharField(max_length=15)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField()),
                ('localidad', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
